Algoritmo "calcular_o_dobro"
// Disciplina   : [Algoritmo]
// Professor   : MARCOS ALVES MARIANO
// Descrição   : Recebe um valor inteiro e calcula o dobro
// Autor(a)    : Renan Francisco Magalhães Gatti
// Data atual  : 19/10/2022
Var
   valor, resultado : inteiro


Inicio
      escreva("Digite o valor para calcular: ")
      leia(valor)
      
      resultado <- valor * 2
      
      escreval("O dobro de ", valor, " é ", resultado)
      


Fimalgoritmo