Algoritmo "exercicio_idade"

Var
   nome1, nome2 : caractere
   idade1, idade2, media : real

Inicio
      Escreva("Qual o nome da primeira pessoa:")
      leia(nome1)
      Escreva("Qual a idade da primeira pessoa:")
      leia(idade1)
      escreva("Qual o nome da segunda pessoa:")
      leia(nome2)
      escreva("Qual a idade da segunda pessoa:")
      leia(idade2)
         media <- (idade1 + idade2) / 2
      escreva("A idade média das pessoas é: ", media, ". ")
      


Fimalgoritmo