Algoritmo "Maior_ou_Menor_de_idade"
// Disciplina   : [Algoritmos]
// Professor   : MARCOS ALVES MARIANOi
// Descrição   : Programa que informa se a pessoa é maior ou menor de idade
// Autor(a)    : Renan Francisco Magalhães Gatti
// Data atual  : 20/10/2022
Var
   idade : inteiro


Inicio
escreva("Qual a idade: ")
leia(idade)

se (idade < 18) entao
   escreva("É menor de idade")
   senao
        escreva("É maior de idade")
fimse


Fimalgoritmo