Algoritmo "mostrar_pares"
// Disciplina   : [Algoritmo]
// Professor   : MARCOS ALVES MARIANO
// Descrição   : Mostra os numeros pares de 0 a 20
// Autor(a)    : Renan Francisco Magalhães Gatti
// Data atual  : 21/10/2022

Var
i : inteiro


Inicio
i <- 0

escreval("Numeros pares de 0 a 20:")

enquanto (i <= 20) faca
         se (i % 2 = 0) entao
         escreval(i)
         fimse
         i <- i + 1
fimenquanto

Fimalgoritmo